version: '3.8'
services:
  db:
    image: postgres:17-alpine
    container_name: postgres17
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata17:/var/lib/postgresql/data
volumes:
  pgdata17:
