version: "3.8"

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2023-03-20T20-16-18Z
    container_name: minio
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Web UI
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_URL}
    command: server /data --console-address ":9001"
    volumes:
      - ${MINIO_DATA_DIR}:/data
    restart: unless-stopped
